# Generated by Django 2.2.11 on 2020-04-06 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200407_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skilltype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='skills',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Skilltype'),
        ),
    ]
