# Generated by Django 2.2.11 on 2020-04-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200407_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='time',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
